### ISSUE TITLE
Upgrade Symfony Components to ^6

### ISSUE THREAD

**Issue by gsteel** [netglue/laminas-messenger#144]

**Comment by pimjansen** [comment]
Would like to see this @gsteel any help you need?

**Comment by gsteel** [comment]
Hi @pimjansen 

Me too! I just haven't had the time to work on it. Some help would be very much appreciated.

I've filed this in the 2.0 milestone because there are some breaking changes that'll be forced on us due to signature changes in Symfony stuff somewhere - I can't remember exactly where.

I'd start by dropping PHP 8.0 and getting PHPUnit upgraded to 10 with `displayDeprecations` to see exactly where the Symfony deprecations are. That can be done for `1.5.0` and hopefully it'll at least reveal where the BC breaks are.
